name: CI

# edit 1
on:
  push:
    branches:
      - feature
  pull_request:
    branches: 
      - feature

jobs:   
    build:
        name: Call Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/muthuluri-janakimuthuluri-janaki0526/Sonarcloud
            azure-pipeline-name: 'Sonarcloud'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN1 }}
